# Generated by Django 5.1.6 on 2025-04-29 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteMgmt', '0002_alter_post_featured_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
