# Generated by Django 5.1.6 on 2025-04-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMgmt', '0003_remove_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ManyToManyField(to='siteMgmt.category'),
        ),
    ]
