# Generated by Django 5.1.6 on 2025-04-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMgmt', '0004_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Change Me', max_length=500, null=True),
        ),
    ]
