# Generated by Django 5.1.6 on 2025-06-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteMgmt', '0005_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='affiliate_link',
            field=models.URLField(default='https://t.me/bilboardmusic', max_length=500),
            preserve_default=False,
        ),
    ]
